name: CICD demo

on:
  push:
    branches:
      - master

env:
  AWS_REGION: ap-south-1
  ECR_REGISTRY: 288408890206.dkr.ecr.ap-south-1.amazonaws.com
  IMAGE_NAME: demp

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build Docker image
      run: |
        docker build -t $ECR_REGISTRY/dibops:demo .     
    - name: Push Docker image to ECR
      run: |
        docker push $ECR_REGISTRY/dibops:demo
