
name: erp-lms-service

on:
  push:
    branches:
      - feature/obi/test

jobs:
  deploy-Container:
    runs-on: ubuntu-latest
    steps:
    - name: Notify Slack
      uses: asconsoft/action-slack@v4.0.1
      with:
        channel: '#deployment'
        if_mention: failure,cancelled
        status: ${{ job.status }}
        fields: workflow,job,commit,repo,ref,author
        text_success: ':rocket: `erp-lms` is successfully deployed in an EC2 instance'
        text_failure: ':boom: `erp-lms` has failed to be deployed :-1:; working on it :hammer_and_wrench:'
      env:
        SLACK_GIT_TOKEN: ${{ secrets.SLACK_GIT_TOKEN }} # optional
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      if: always() # Pick up events even if the job fails or is canceled.       
        
            
