
name: Obi Test

on:
  push:
    branches:
      - feature/obi

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install SSH client
      run: sudo apt-get install openssh-client
    #- name: Add EC2 to known hosts
    #  run: ssh-keyscan -H 13.235.39.142> >> ~/.ssh/known_hosts
    - name: SSH to EC2 and run commands
      env:
        EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
      run: |
        ssh -i ${{ secrets.EC2_PRIVATE_KEY }} ec2-user@13.235.39.142 "echo Hello world!"
       # ssh -i ${{ secrets.EC2_PRIVATE_KEY }}  -o "StrictHostKeyChecking no" ec2-user@13.235.39.142 "docker pull $ECR_REGISTRY/onebillionideas:${IMAGE_TAG} && docker run -d -p 8080:8080 $ECR_REGISTRY/onebillionideas:${IMAGE_TAG}"
