name: AI Code Review with Tabby

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write  # 🔑 Needed to post PR comments

jobs:
  tabby-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 🔁 Ensures full git history for diff

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r ai-review/requirements.txt

      - name: Run Tabby PR review
        env:
          TABBY_URL: ${{ secrets.TABBY_URL }}
          TABBY_USERNAME: ${{ secrets.TABBY_USERNAME }}
          TABBY_PASSWORD: ${{ secrets.TABBY_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
        run: python ai-review/review_bot.py
